
stages:
  - run
  - test
      
run_mc_uuu:
  stage: run
  image: cern/cc7-base
  before_script:
    - printf $SERVICE_PASS | kinit $CERN_USER@CERN.CH
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc8-opt/setup.sh
    - cd test
    - mkdir output
    - bash test_mc_uuu.sh
    - python --version
  artifacts:
    paths:
      - test/output
    expire_in: 1 week
