
stages:
  - run
  - test
      
run_mc_uuu:
  stage: run
  image: gitlab-registry.cern.ch/sft/docker:lcg-cc7
  before_script:
    - printf $SERVICE_PASS | kinit $CERN_USER@CERN.CH
  script:
    - source setup.sh
    - cd test
    - mkdir output
    - bash test_mc_uuu.sh
    - python --version
  artifacts:
    paths:
      - test/output
    expire_in: 1 week
